language: r
cache: packages
r_check_args: --no-manual

r:
  - release

r_packages:
  - covr
  - testthat
  - usethis

after_success:
  - Rscript -e 'covr::codecov()'

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: *.tar.gz
  skip_cleanup: true
  on:
    tags: true



